<b>Arrays in python</b>

In [4]:
import array
my_a=array.array('i',[1,2,3,4,4])
my_a

array('i', [1, 2, 3, 4, 4])

In [6]:
my_f=array.array('f',[1,2,3,4,4])
my_f

array('f', [1.0, 2.0, 3.0, 4.0, 4.0])

In [8]:
import numpy as np

arr =np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
zero_arr= np.array(50)

In [11]:
zero_arr


array(50)

In [13]:
twod_arr= np.array([[3,4,5,6],[5,6,6,77]])
twod_arr


array([[ 3,  4,  5,  6],
       [ 5,  6,  6, 77]])

In [18]:

int_list= [3,4,5,6, 3.5, "hi"]
my_int_array = np.array(int_list)

In [19]:
my_int_array


array(['3', '4', '5', '6', '3.5', 'hi'], dtype='<U32')

In [21]:
my_int_array.dtype

dtype('<U32')

In [22]:
my_int_array.ndim

1

In [23]:
twod_arr.ndim


2

In [24]:
twod_arr.tolist()

[[3, 4, 5, 6], [5, 6, 6, 77]]

In [25]:
my_int_array.tolist()

['3', '4', '5', '6', '3.5', 'hi']

In [26]:
len(my_int_array)

6

In [27]:
my_int_array.size

6

In [28]:
my_int_array.shape


(6,)

In [29]:
twod_arr.shape

(2, 4)

In [32]:
zeros = np.zeros(6,)
zeros

array([0., 0., 0., 0., 0., 0.])

In [34]:
zeros_int = np.zeros(6, dtype=int)
zeros_int

array([0, 0, 0, 0, 0, 0])

In [35]:
one_arr= np.ones(9)

In [36]:
one_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.empty(10)

array([0.00000000e+000, 1.00937611e-320, 0.00000000e+000, 0.00000000e+000,
       5.83198137e+252, 2.00620165e-052, 7.48419171e-067, 7.42381949e-091,
       6.24192196e-042, 5.21506443e-310])

In [39]:
arrange_arr= np.arange(1,10)
arrange_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [45]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
#2D arrays

l1= [3,4,55]
l2= [3,45,5,5]
two_d_array = np.array([l1,l2], dtype=object)
two_d_array

array([list([3, 4, 55]), list([3, 45, 5, 5])], dtype=object)

In [54]:
two_d_array.ndim

1

In [55]:
two_d_array.dtype

dtype('O')

In [51]:
two_d_array.size


2

In [1]:
two_d_array.shape

NameError: name 'two_d_array' is not defined

In [56]:
l1=[1,2,3,4,5]
a1= np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [57]:
a1[2]

3

In [58]:
a1[-1]

5

In [62]:
a1[2]=777

In [63]:
a1

array([  1,   2, 777,   4,   5])

In [64]:
a1[:2]

array([1, 2])

In [65]:
a2

NameError: name 'a2' is not defined

In [68]:
a2 = np.array([[1,2,34,],[3,4,5,6]])
a2

/var/folders/c3/bw987b155ynfs7xrh5_pt9t40000gn/T/ipykernel_4444/1914774881.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1,2,34,],[3,4,5,6]])


array([list([1, 2, 34]), list([3, 4, 5, 6])], dtype=object)

In [69]:
a_sub= a1[:3]

In [70]:
a_sub


array([  1,   2, 777])

In [71]:
type(a_sub)

numpy.ndarray

In [72]:
a_sub[0]

1

In [73]:
a_sub[0]=100

In [74]:
a_sub


array([100,   2, 777])

In [75]:
a1

array([100,   2, 777,   4,   5])

In [76]:
a_copy =a1.copy()

In [77]:
a_copy


array([100,   2, 777,   4,   5])

In [78]:
a_copy[2]=200

In [79]:
a_copy

array([100,   2, 200,   4,   5])

In [80]:
a1

array([100,   2, 777,   4,   5])

<b>Reshapping</b>

In [234]:
oned_array = np.array([1,5,6,7,7,8,8,64,34,333,3,2])
oned_array

array([  1,   5,   6,   7,   7,   8,   8,  64,  34, 333,   3,   2])

In [85]:
one_arr.size

9

In [86]:
one_arr.ndim


1

In [242]:
two_d_array = oned_array.reshape(4,3)
two_d_array

array([[  1,   5,   6],
       [  7,   7,   8],
       [  8,  64,  34],
       [333,   3,   2]])

In [240]:
two_d_array = oned_array.reshape(2,6)
two_d_array

array([[  1,   5,   6,   7,   7,   8],
       [  8,  64,  34, 333,   3,   2]])

In [98]:
import sys
sys.version

'3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'

In [119]:
ar1 = np.arange(1, 10000)
%timeit sum(ar1)


704 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
%timeit np.sum(ar1)

2.99 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [120]:
a1+5

array([105,   7, 782,   9,  10])

In [121]:
np.add(a1,2)

array([102,   4, 779,   6,   7])

In [243]:
two_d_array


array([[  1,   5,   6],
       [  7,   7,   8],
       [  8,  64,  34],
       [333,   3,   2]])

In [125]:
a2 = np.array([[1,2,3],[4,5,6]])

In [127]:
np.sum(a2, axis=0)

array([5, 7, 9])

In [244]:
np.sum(a2, axis=1)

array([ 6, 15])

In [129]:
a1

array([100,   2, 777,   4,   5])

In [130]:
a2 == 4

array([[False, False, False],
       [ True, False, False]])

In [131]:
a1 != 100

array([False,  True,  True,  True,  True])

In [132]:
a1==a2

/var/folders/c3/bw987b155ynfs7xrh5_pt9t40000gn/T/ipykernel_4444/3426729955.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1==a2


False

In [136]:
np.all(a1>1)

True

In [134]:
a1


array([100,   2, 777,   4,   5])

In [138]:
np.any(a1>776)

True

In [139]:
a1.min()

2

In [140]:
a2.max()



6

In [141]:
a1.std()

302.0149665165619

In [142]:
a1.mean()

177.6

In [143]:
a1.var()

91213.04000000001

In [144]:
a1.sort()

In [260]:
array_1= np.array([1,4,8,100,200])
print(array_1)
np.sum((array_1[array_1 > 8]))# expecting 300 as a sum  

[  1   4   8 100 200]


300

In [180]:
 np.sum(a1)

888

In [173]:
a1


array([  2,   4,   5, 100, 777])

In [157]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<b>Pandas</b>

In [181]:
import pandas as pd

In [182]:
pd.__version__


'1.3.4'

In [186]:
np.__version__



'1.20.3'

In [187]:
dic = {"one": [1,2,3,4]}

In [188]:
type(dic)

dict

In [189]:
my_series = pd.Series(dic)

In [190]:
type(my_series)

pandas.core.series.Series

In [191]:
my_series

one    [1, 2, 3, 4]
dtype: object

In [192]:
aa = np.random.randint(5, size=10)

In [193]:
aa

array([2, 3, 1, 0, 2, 3, 0, 0, 3, 3])

In [194]:
series1 = pd.Series(aa)

In [195]:
series1

0    2
1    3
2    1
3    0
4    2
5    3
6    0
7    0
8    3
9    3
dtype: int64

In [203]:
dict = {
    "id":[1,2,3,4, 5], "name":["a","s","d","f","s"]
}

In [197]:
type(dict)

dict

In [204]:
df = pd.DataFrame(dict)

In [205]:
df

id name
0   1    a
1   2    s
2   3    d
3   4    f
4   5    s

In [210]:
df.columns

Index(['id', 'name'], dtype='object')

In [213]:
df.dtypes

id       int64
name    object
dtype: object

In [214]:
users= pd.read_csv("user.csv")

In [215]:
users

id  active  \
0     auth0|5b28a85508de1a4228a84092    True   
1     auth0|5b28aeae0cbf6f1e2bec50d8    True   
2     auth0|5b28aeaf0cbf6f1e2bec50eb    True   
3     auth0|5b28a12508de1a4228a831ef    True   
4     auth0|5b28c4eb8702af037db95752    True   
...                              ...     ...   
1044  auth0|61b1f26e36407f007184a729    True   
1045  auth0|61b1f2733a87c80068374844    True   
1046  auth0|61b1f28a08dd210072ee4b09    True   
1047  auth0|61b1f28f16651f006a398def    True   
1048  auth0|61b1f2f47b73890070820978    True   

                                 notification_cc_emails created_by  \
0                              ["Minh.TUYET@Coats.com"]   migrated   
1                                 ["thuy.vo@coats.com"]   migrated   
2     ["hien.nguyentt@coats.com", "ngocnhan@ducthanh...   migrated   
3     ["Dep.HUYNH@coats.com", "camy.vn@bodynits.com"...   migrated   
4                                                  [""]   migrated   
...                                                 ...        ...   
1044                             ["thu.ngoc@coats.com"]   migrated   
1045                             ["thu.ngoc@coats.com"]   migrated   
1046   ["Tuyen.nguyen@coats.com", "lan.pham@coats.com"]   migrated   
1047                             ["thu.ngoc@coats.com"]   migrated   
1048                        ["hien.nguyentt@coats.com"]   migrated   

                         created_at               updated_by  \
0     2018-06-19 12:21:29.753 +0530  auth0-user-sync-process   
1     2018-06-19 12:49:49.137 +0530  auth0-user-sync-process   
2     2018-06-19 12:49:49.136 +0530  auth0-user-sync-process   
3     2018-06-19 11:51:54.521 +0530  auth0-user-sync-process   
4     2018-06-19 14:24:54.575 +0530  auth0-user-sync-process   
...                             ...                      ...   
1044  2021-12-09 17:41:26.132 +0530  auth0-user-sync-process   
1045  2021-12-09 17:41:31.308 +0530  auth0-user-sync-process   
1046  2021-12-09 17:41:54.930 +0530  auth0-user-sync-process   
1047  2021-12-09 17:41:59.188 +0530  auth0-user-sync-process   
1048  2021-12-09 17:43:40.138 +0530  auth0-user-sync-process   

                         updated_at       first_name          last_name  \
0     2021-12-03 17:30:09.114 +0530           Ms Nhi       0977 341 722   
1     2021-11-03 14:30:02.276 +0530  MERRY ( THANH)           706660346   
2     2021-12-10 17:10:58.110 +0530               Mr                Tra   
3     2021-10-15 14:18:12.046 +0530         Ms. Kite                 --   
4     2021-12-03 17:30:09.117 +0530           Nguyen               Vien   
...                             ...              ...                ...   
1044  2021-12-09 18:30:13.572 +0530         Ms Dương      01696 993 219   
1045  2021-12-09 18:30:13.565 +0530               Mr   Vinh 01228782802   
1046  2021-12-11 07:30:06.313 +0530               My                Anh   
1047  2021-12-22 13:30:06.367 +0530              Kim  Hanh 0972 332 704   
1048  2021-12-09 18:30:13.477 +0530     Ms. Thu Thủy                NaN   

                                     email  ... logins_count  user_type role  \
0                   thanh.nguyen@qmico.com  ...            0         EX  USR   
1                           mery@wondo.net  ...            1         EX  USR   
2               phuoctra@ducthanhkl.com.vn  ...           11         EX  USR   
3                     kite.vn@bodynits.com  ...            0         EX  USR   
4                    nguyen.vien@qmico.com  ...            0         EX  USR   
...                                    ...  ...          ...        ...  ...   
1044  merch_5_thuyduong@royalspirit.com.vn  ...            0         EX  USR   
1045  merch_9_lucamvinh@royalspirit.com.vn  ...            0         EX  USR   
1046                    process@igm-vn.com  ...            1         EX  USR   
1047               purch_hanale@dbw.com.vn  ...            3         EX  USR   
1048           thuthuy.merch@demcovina.com  ...            0      

In [217]:
users.user_type

0       EX
1       EX
2       EX
3       EX
4       EX
        ..
1044    EX
1045    EX
1046    EX
1047    EX
1048    EX
Name: user_type, Length: 1049, dtype: object

In [221]:
short_users = ["id", "email","user_type"]
users.iloc[3,4]

'2018-06-19 11:51:54.521 +0530'

In [223]:
users.loc[3]

id                                                       auth0|5b28a12508de1a4228a831ef
active                                                                             True
notification_cc_emails                ["Dep.HUYNH@coats.com", "camy.vn@bodynits.com"...
created_by                                                                     migrated
created_at                                                2018-06-19 11:51:54.521 +0530
updated_by                                                      auth0-user-sync-process
updated_at                                                2021-10-15 14:18:12.046 +0530
first_name                                                                     Ms. Kite
last_name                                                                            --
email                                                              kite.vn@bodynits.com
language                                                                        ENGLISH
enable_monthly_invoice_report   

In [225]:
users[users.user_type=='IN']

Empty DataFrame
Columns: [id, active, notification_cc_emails, created_by, created_at, updated_by, updated_at, first_name, last_name, email, language, enable_monthly_invoice_report, customer_sales_orgs, monthly_invoice_report_sent, contact_number, country_code, date_format, time_format, number_format, time_zone, terms_and_conditions_accepted_date, enable_order_acknowledgement_email, enable_advance_shipment_notice, enable_payment_pre_reminder, enable_payment_alert, enable_immediate_order_update, never_authenticated, ship_to_parties, logins_count, user_type, role, reminder_count, last_reminder_sent, enable_welcome_email, id.1, sales_org, customer_code, customer_name]
Index: []

[0 rows x 38 columns]

In [226]:
users[users.logins_count >10]

id  active  \
2    auth0|5b28aeaf0cbf6f1e2bec50eb    True   
5    auth0|5b4ee604fc239962a3710960    True   
6    auth0|5bfe5359598e1c11a8a15f30    True   
7    auth0|611a5421390ec4006983d3ee    True   
9    auth0|611ba581bf348b006bb548c9    True   
10   auth0|611ba5872420250069c6fe54    True   
11   auth0|611cf52cbde6b80068060292    True   
38   auth0|5e5393af3ef7000e8ce81e6e    True   
41   auth0|611a542a3ae8e50069658bd7    True   
57   auth0|614088c61780e5006abb62e2    True   
68   auth0|6143351440e735007113ab55    True   
69   auth0|615ac373b8e7cc006addbc58    True   
80   auth0|615bd889be378400718c2c70    True   
97   auth0|6141d60e01c641006a527084    True   
140  auth0|61641efe2caee800716de3c5    True   
143  auth0|61641f07150257007028e784    True   
160  auth0|618bde498d4f40006980cd2b    True   
237  auth0|61963d14aa6a67007212f93f    True   
257  auth0|610a7f42edeb770072e10f80    True   
574  auth0|6164069b560d9b00686fc8da    True   
824  auth0|60f80e333cd751006900f001    True   
825  auth0|60f8e5dc838de9006a987e49   False   
828  auth0|61111f58621f9600684f5cbe    True   
841  auth0|611cf526401a000076c62e54    True   
860  auth0|6141d60027ab250069a79ae8    True   
863  auth0|6143350f52787f0069713ac6    True   
864  auth0|61545150b8e7cc006aa62c30    True   
869  auth0|615d56e79deb4e006965a675    True   
874  auth0|615edf1b25167900699fe2a5    True   
880  auth0|615edfb604e61a0071093f58    True   
884  auth0|616d383af4c52c006878a207    True   
973  auth0|61a75b4f359877007131c40e    True   

                                notification_cc_emails  \
2    ["hien.nguyentt@coats.com", "ngocnhan@ducthanh...   
5    ["Dep.HUYNH@coats.com", "buithibichngoc@trista...   
6                                 ["hoa.ho@coats.com"]   
7      ["hoa.ho@coats.com", "huong.th.pham@coats.com"]   
9                               ["lan.pham@coats.com"]   
10   ["Hien.NGUYENTT@coats.com", "huong.th.pham@coa...   
11                              ["lan.pham@coats.com"]   
38                          ["tuyen.nguyen@coats.com"]   
41   ["thu.ngoc@coats.com", "van.purchase01@vastapp...   
57   ["hien.nguyentt@coats.com", "hientp@thanhcong....   
68   ["tuyen.nguyen@coats.com", "lyna.pei01@eclat.c...   
69   ["Dep.HUYNH@coats.com", "Thuy.vn@bodynits.com"...   
80                             ["dep.huynh@coats.com"]   
97   ["austin.zeng@eclat.com.tw", "kieuoanh.phan@ec...   
140     ["tmv29@tmv.com.vn", "tuyen.nguyen@coats.com"]   
143                             ["thu.ngoc@coats.com"]   
160                            ["tran.phan@coats.com"]   
237                               ["hoa.ho@coats.com"]   
257  ["hoa.ho@coats.com", "vancth@anhuco.com", "huo...   
574         ["hoa.ho@coats.com", "huongct@anhuco.com"]   
824                              ["thuy.vo@coats.com"]   
825                                                 []   
828                             ["thu.ngoc@coats.com"]   
841                               ["hoa.ho@coats.com"]   
860  ["thuy.vo@coats.com", "mya.le@vn.asmaragroup.c...   
863                         ["thanh.trantt@coats.com"]   
864        ["thu.ngoc@coats.com", "Anh.LAN@coats.com"]   
869      ["stock.vn@l-t-p.com", "dep.huynh@coats.com"]   
874                             ["thu.ngoc@coats.com"]   
880        ["thu.ngoc@coats.com", "Anh.LAN@coats.com"]   
884  ["thanh.trantt@coats.com", "van.pham@coats.com...   
973                                                 []   

                         created_by                     created_at  \
2                          migrated  2018-06-19 12:49:49.136 +0530   
5                          migrated  2018-07-18 12:32:28.439 +0530   
6                          migrated  2018-11-28 14:05:37.591 +0530   
7                          migrated  2021-08-16 17:33:45.097 +0530   
9                          migrated  2021-08-17 17:33:13.739 +0530   
10                         migrated  2021-08-17 17:33:19.198 +0530   
11                         migrated  2021-08-18 17:25:24.668 +0530   
38    

In [231]:
users.query("first_name == 'Hai'")

id  active  \
28  auth0|5b28a85a08de1a4228a84101    True   
38  auth0|5e5393af3ef7000e8ce81e6e    True   

                               notification_cc_emails created_by  \
28  ["lieu.le@coats.com", "thanhbinh@donagamex.com...   migrated   
38                         ["tuyen.nguyen@coats.com"]   migrated   

                       created_at               updated_by  \
28  2018-06-19 12:21:29.745 +0530  auth0-user-sync-process   
38  2020-02-24 14:43:19.856 +0530  auth0-user-sync-process   

                       updated_at first_name           last_name  \
28  2021-10-15 14:18:11.304 +0530        Hai  Tech4: 01273933158   
38  2021-12-27 10:30:07.504 +0530        Hai              Nguyen   

                       email  ... logins_count  user_type role reminder_count  \
28    tech4@donagamex.com.vn  ...            0         EX  USR              4   
38  hai.nguyen@klf-group.com  ...          106         EX  USR              0   

               last_reminder_sent enable_welcome_email  \
28  2021-11-01 05:30:14.385 +0530                 True   
38                            NaN                 True   

                              id.1 sales_org customer_code  \
28  auth0|5b28a85a08de1a4228a84101      VN50        119274   
38  auth0|5e5393af3ef7000e8ce81e6e      VN50        119306   

                        customer_name  
28  CTY CO PHAN TONG CTY MAY DONG NAI  
38        CONG TY TNHH MAY MAC TOPTEX  

[2 rows x 38 columns]